
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway-depl
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      volumes:
      - name: "krakend-config"
        configMap:
           name: "krakend-config"
      containers:
      - name: gateway-svc
        command: ["/gateway-svc", "-c", "/etc/krakend/krakend.json"]
        image: 755455355830.dkr.ecr.us-east-2.amazonaws.com/gateway-svc
        env:
        - name: DB_SERVER
          value: "meem-db-instance.c8qfd5ux55rw.us-east-2.rds.amazonaws.com"
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        #ports:
        #- containerPort: 1883
        #imagePullPolicy: Always
        imagePullPolicy: Never
        ports:
        - name: gateway-svc
          containerPort: 8180
        volumeMounts:
        - name: "krakend-config"
          mountPath: "/etc/krakend"

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-srvc
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
  - port: 8180
    targetPort: gateway-svc
